import type { Archetype } from "@cv-builder/schemas";

export const dataMlEngineer: Archetype = {
  id: "data-ml-engineer",
  name: "Data & ML Engineer",
  description: "Engineers building data pipelines and machine learning systems",
  keywords: [
    "python",
    "sql",
    "spark",
    "airflow",
    "dbt",
    "pandas",
    "pytorch",
    "tensorflow",
    "scikit-learn",
    "feature engineering",
    "etl",
    "data pipeline",
    "warehouse",
    "snowflake",
    "bigquery",
    "mlops",
    "model serving",
    "experiment tracking",
  ],
  evaluationWeights: {
    shippedEvidence: 0.25,
    quantifiedImpact: 0.2,
    toolingVisibility: 0.25,
    atsCompatibility: 0.1,
    keywordMatch: 0.1,
    publicProof: 0.1,
  },
  actionVerbs: [
    "Built",
    "Trained",
    "Deployed",
    "Productionized",
    "Optimized",
    "Automated",
    "Modeled",
    "Scaled",
  ],
  antiPatterns: [
    "familiar with machine learning",
    "exposure to data science",
    "worked with big data",
    "passionate about AI",
  ],
  version: "1.0.0",
};
