import type { Archetype } from "@cv-builder/schemas";

export const productManager: Archetype = {
  id: "product-manager",
  name: "Product Manager",
  description: "Product managers owning discovery, roadmap, and delivery",
  keywords: [
    "roadmap",
    "discovery",
    "user research",
    "a/b testing",
    "experiment",
    "okrs",
    "kpis",
    "retention",
    "activation",
    "funnel",
    "churn",
    "stakeholder",
    "prioritization",
    "agile",
    "amplitude",
    "mixpanel",
    "go-to-market",
    "pricing",
  ],
  evaluationWeights: {
    shippedEvidence: 0.25,
    quantifiedImpact: 0.25,
    toolingVisibility: 0.1,
    atsCompatibility: 0.15,
    keywordMatch: 0.15,
    publicProof: 0.1,
  },
  actionVerbs: [
    "Launched",
    "Owned",
    "Drove",
    "Grew",
    "Defined",
    "Prioritized",
    "Increased",
    "Reduced",
  ],
  antiPatterns: [
    "passionate about products",
    "leveraged synergies",
    "aligned stakeholders",
    "wore many hats",
    "helped with",
  ],
  version: "1.0.0",
};
