import type { Archetype } from "@cv-builder/schemas";

export const softwareEngineer: Archetype = {
  id: "software-engineer",
  name: "Software Engineer",
  description: "Frontend, backend, and full-stack engineers building software",
  keywords: [
    "typescript",
    "javascript",
    "python",
    "go",
    "java",
    "react",
    "node",
    "postgres",
    "redis",
    "kafka",
    "docker",
    "kubernetes",
    "aws",
    "ci/cd",
    "microservices",
    "rest",
    "graphql",
    "testing",
    "system design",
  ],
  evaluationWeights: {
    shippedEvidence: 0.3,
    quantifiedImpact: 0.2,
    toolingVisibility: 0.2,
    atsCompatibility: 0.1,
    keywordMatch: 0.1,
    publicProof: 0.1,
  },
  actionVerbs: [
    "Built",
    "Shipped",
    "Designed",
    "Scaled",
    "Optimized",
    "Migrated",
    "Automated",
    "Refactored",
  ],
  antiPatterns: [
    "familiar with",
    "exposure to",
    "team player",
    "fast learner",
    "responsible for various tasks",
  ],
  version: "1.0.0",
};
